### ISSUE TITLE
Failed to load RouteConnector Plugin

### ISSUE THREAD

**Issue by srafay** [Basssiiie/Random-Race-Generator#1]
Hey, I wanted to try out your filterscript (seems cool).
I am having problems while loading the Route Connector plugin.

> [19:18:03]  Loading plugin: RouteConnectorPlugin.so
> [19:18:03]   Failed (libtbb.so.2: wrong ELF class: ELFCLASS64)

How could I fix this, thanks!

**Comment by Basssiiie** [comment]
Hey there, I'm no pro on Linux but it seems you need the 32-bit libraries of IntelTBB on your Linux server. (Right now it seems only 64-bit is there.) More info here: [click](https://github.com/Basssiiie/Random-Race-Generator#the-server-log-reports-failed-libtbbso2-cannot-open-shared-object-file-no-such-file-or-directory), it's about the same library file.

Let me know if it helps.

**Comment by srafay** [comment]
Sure, i will let you know if anything works for me.
